spring:
  datasource:
    url: jdbc:h2:mem:DistributionDB

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    ROOT: INFO
  file:
    name: log.log

application:
  url: "https://www.cbr-xml-daily.ru/daily_json.js"
  fileCurrencies: "currencies.csv"