DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES
(
    ID            BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME          VARCHAR(255) NOT NULL,
    BALANCE       DECIMAL(20, 2),
    PERCENT       DECIMAL(20, 2),
    PURPOSEAMOUNT DECIMAL(20, 2) DEFAULT 0.00,
    COMMENT       VARCHAR(255),
    ACTIVE        INT(1)
);

DROP TABLE IF EXISTS EXPENSE;
CREATE TABLE EXPENSE
(
    ID          BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORY BIGINT references CATEGORIES (ID) on delete cascade,
    AMOUNT      DECIMAL(20, 2),
    DATE        DATE
);

DROP TABLE IF EXISTS INCOME;
CREATE TABLE INCOME
(
    ID          BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORY BIGINT references CATEGORIES (ID) on delete cascade,
    AMOUNT      DECIMAL(20, 2),
    DATE        DATE
);

DROP TABLE IF EXISTS EXCHANGE_RATE;
CREATE TABLE EXCHANGE_RATE
(
    ID    BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME  VARCHAR(10) NOT NULL,
    PRICE DECIMAL(20, 2),
    DATE  DATE DEFAULT CURRENT_DATE
);

DROP TABLE IF EXISTS BALANCES;
CREATE TABLE BALANCES
(
    ID    BIGINT      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORY BIGINT references CATEGORIES (ID) on delete cascade,
    VALUTE VARCHAR(255),
    BALANCE DECIMAL(20, 2),
    DATE  DATE DEFAULT CURRENT_DATE
);
